# Generated by Django 6.0 on 2025-12-12 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("core", "0001_initial"),
        ("datasets", "0001_initial"),
        ("visualizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "layout",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Grid/widget layout configuration",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dashboard settings and preferences",
                    ),
                ),
                (
                    "auto_insights_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable automatic insight generation"
                    ),
                ),
                (
                    "insight_refresh_interval",
                    models.IntegerField(
                        default=3600,
                        help_text="Insight refresh interval in seconds (default: 1 hour)",
                    ),
                ),
                ("last_insight_refresh", models.DateTimeField(blank=True, null=True)),
                (
                    "interpretability_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable SHAP/LIME analysis for predictions",
                    ),
                ),
                (
                    "interpretability_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("shap", "SHAP"),
                            ("lime", "LIME"),
                            ("both", "Both SHAP and LIME"),
                        ],
                        default="shap",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as template for creating new dashboards",
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "datasets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Datasets to monitor for insights",
                        related_name="dashboards",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visualizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dashboards",
                        to="visualizations.visualization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("summary", "Summary Statistics"),
                            ("trend", "Trend Analysis"),
                            ("anomaly", "Anomaly Detection"),
                            ("correlation", "Correlation Analysis"),
                            ("prediction", "Predictive Insights"),
                            ("performance", "Performance Metrics"),
                            ("alert", "Alert/Warning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Insight data and metrics"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Additional metadata"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence score (0.0 to 1.0)"
                    ),
                ),
                (
                    "is_actionable",
                    models.BooleanField(
                        default=False, help_text="Requires user action"
                    ),
                ),
                ("action_taken", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this insight becomes stale",
                        null=True,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_insights",
                        to="core.dashboard",
                    ),
                ),
                (
                    "source_datasets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dashboard_insights",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "source_insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_insights",
                        to="analytics.insight",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("edit", "Can Edit"),
                            ("admin", "Admin"),
                        ],
                        default="view",
                        max_length=10,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="core.dashboard",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards_shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("insight", "Insight Card"),
                            ("visualization", "Visualization"),
                            ("metric", "Metric Display"),
                            ("anomaly", "Anomaly Alert"),
                            ("trend", "Trend Chart"),
                            ("table", "Data Table"),
                            ("text", "Text/Markdown"),
                            ("iframe", "Embedded Content"),
                            ("interpretability", "ML Interpretability"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Widget-specific configuration"
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=4)),
                ("height", models.IntegerField(default=3)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-refresh interval in seconds (0 = no refresh)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="core.dashboard",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_widgets",
                        to="analytics.insight",
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_widgets",
                        to="analytics.metric",
                    ),
                ),
                (
                    "visualization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_widgets",
                        to="visualizations.visualization",
                    ),
                ),
            ],
            options={
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="InterpretabilityAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("shap_values", "SHAP Values"),
                            ("shap_summary", "SHAP Summary Plot"),
                            ("shap_dependence", "SHAP Dependence Plot"),
                            ("lime_explanation", "LIME Explanation"),
                            ("feature_importance", "Feature Importance"),
                            ("partial_dependence", "Partial Dependence"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("model_name", models.CharField(blank=True, max_length=255)),
                ("model_type", models.CharField(blank=True, max_length=100)),
                (
                    "results",
                    models.JSONField(
                        default=dict, help_text="Analysis results and data"
                    ),
                ),
                (
                    "visualization_data",
                    models.JSONField(
                        default=dict,
                        help_text="Data for visualizing interpretability results",
                    ),
                ),
                (
                    "feature_names",
                    models.JSONField(default=list, help_text="List of feature names"),
                ),
                (
                    "feature_importances",
                    models.JSONField(
                        default=dict, help_text="Feature importance scores"
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=0, help_text="Number of samples analyzed"
                    ),
                ),
                (
                    "computation_time",
                    models.FloatField(
                        default=0.0, help_text="Time taken to compute (seconds)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretability_analyses",
                        to="core.dashboard",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretability_analyses",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Interpretability analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["owner", "-updated_at"], name="core_dashbo_owner_i_30a7e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["is_published", "-updated_at"],
                name="core_dashbo_is_publ_50d70b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["is_template"], name="core_dashbo_is_temp_a49f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardinsight",
            index=models.Index(
                fields=["dashboard", "-generated_at"],
                name="core_dashbo_dashboa_83995e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardinsight",
            index=models.Index(
                fields=["dashboard", "priority", "-generated_at"],
                name="core_dashbo_dashboa_d79fbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardinsight",
            index=models.Index(
                fields=["category", "-generated_at"],
                name="core_dashbo_categor_303717_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardshare",
            index=models.Index(
                fields=["shared_with", "-shared_at"],
                name="core_dashbo_shared__bcc90d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardshare",
            index=models.Index(
                fields=["dashboard", "permission_level"],
                name="core_dashbo_dashboa_cb1b17_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboardshare",
            unique_together={("dashboard", "shared_with")},
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["dashboard", "widget_type"],
                name="core_dashbo_dashboa_d0b305_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardwidget",
            index=models.Index(
                fields=["dashboard", "position_y", "position_x"],
                name="core_dashbo_dashboa_9e1016_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interpretabilityanalysis",
            index=models.Index(
                fields=["dashboard", "analysis_type", "-created_at"],
                name="core_interp_dashboa_714893_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interpretabilityanalysis",
            index=models.Index(
                fields=["dataset", "-created_at"], name="core_interp_dataset_db7607_idx"
            ),
        ),
    ]
