# Generated by Django 6.0 on 2025-12-04 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('trend', 'Trend Analysis'), ('correlation', 'Correlation'), ('anomaly', 'Anomaly Detection'), ('distribution', 'Distribution'), ('summary', 'Summary Statistics'), ('forecast', 'Forecast'), ('clustering', 'Clustering'), ('classification', 'Classification')], max_length=20)),
                ('metrics', models.JSONField(default=dict, help_text='Key metrics and values')),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used for analysis')),
                ('confidence_level', models.CharField(choices=[('low', 'Low (0-33%)'), ('medium', 'Medium (34-66%)'), ('high', 'High (67-100%)')], default='medium', max_length=10)),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insights', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='datasets.dataset')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_insight',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('anomaly_type', models.CharField(max_length=100)),
                ('detected_value', models.FloatField()),
                ('expected_range_min', models.FloatField()),
                ('expected_range_max', models.FloatField()),
                ('deviation_score', models.FloatField(help_text='How far from expected range (0-1)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='new', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_anomalies', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='datasets.dataset')),
                ('insight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly', to='analytics.insight')),
            ],
            options={
                'db_table': 'analytics_anomaly',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('alert_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional alert metadata')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='datasets.dataset')),
                ('recipients', models.ManyToManyField(related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('anomaly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='analytics.anomaly')),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='analytics.insight')),
            ],
            options={
                'db_table': 'analytics_alert',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_type', models.CharField(help_text='Type of metric (e.g., sum, average, count)', max_length=100)),
                ('current_value', models.FloatField()),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='datasets.dataset')),
            ],
            options={
                'db_table': 'analytics_metric',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict, help_text='Dashboard layout configuration')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasets', models.ManyToManyField(related_name='analytics_dashboards', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_dashboards', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_analytics_dashboards', to=settings.AUTH_USER_MODEL)),
                ('insights', models.ManyToManyField(blank=True, related_name='analytics_dashboards', to='analytics.insight')),
                ('metrics', models.ManyToManyField(blank=True, related_name='analytics_dashboards', to='analytics.metric')),
            ],
            options={
                'db_table': 'analytics_dashboard',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('summary', 'Summary Report'), ('detailed', 'Detailed Analysis'), ('executive', 'Executive Summary'), ('comparative', 'Comparative Analysis'), ('trend', 'Trend Report'), ('anomaly', 'Anomaly Report')], default='summary', max_length=20)),
                ('content', models.JSONField(default=dict, help_text='Report sections and content')),
                ('metadata', models.JSONField(default=dict, help_text='Report metadata')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('validated', 'Validated'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='datasets.dataset')),
                ('insights', models.ManyToManyField(blank=True, related_name='reports', to='analytics.insight')),
            ],
            options={
                'db_table': 'analytics_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Dataset field being analyzed', max_length=255)),
                ('direction', models.CharField(choices=[('up', 'Upward'), ('down', 'Downward'), ('stable', 'Stable'), ('volatile', 'Volatile')], max_length=20)),
                ('magnitude', models.FloatField(help_text='Rate of change')),
                ('start_value', models.FloatField()),
                ('end_value', models.FloatField()),
                ('average_value', models.FloatField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='datasets.dataset')),
                ('insight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trend', to='analytics.insight')),
            ],
            options={
                'db_table': 'analytics_trend',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['dataset', '-created_at'], name='analytics_i_dataset_79fb51_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['insight_type', '-created_at'], name='analytics_i_insight_dd3e73_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['created_by', '-created_at'], name='analytics_i_created_d5aaf4_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['dataset', 'status', '-detected_at'], name='analytics_a_dataset_0c12a6_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['severity', '-detected_at'], name='analytics_a_severit_9fff4c_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['assigned_to', 'status'], name='analytics_a_assigne_1e61eb_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['dataset', 'status', '-triggered_at'], name='analytics_a_dataset_764a99_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_level', '-triggered_at'], name='analytics_a_alert_l_5779c7_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['dataset', '-measured_at'], name='analytics_m_dataset_799067_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('dataset', 'name')},
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['owner', '-updated_at'], name='analytics_d_owner_i_a287b8_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['is_public', '-updated_at'], name='analytics_d_is_publ_c5c977_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['dataset', '-created_at'], name='analytics_r_dataset_a13f03_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='analytics_r_status_0c5134_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', '-created_at'], name='analytics_r_created_0bd1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['dataset', '-created_at'], name='analytics_t_dataset_d58433_idx'),
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['direction', '-created_at'], name='analytics_t_directi_4831df_idx'),
        ),
    ]
