# Generated by Django 6.0 on 2025-12-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('insight_type', models.CharField(choices=[('relationship', 'Relationship'), ('anomaly', 'Anomaly'), ('pattern', 'Pattern'), ('outlier', 'Outlier'), ('correlation', 'Correlation'), ('distribution', 'Distribution'), ('trend', 'Trend'), ('summary', 'Summary Statistics')], max_length=20)),
                ('analysis_data', models.JSONField(default=dict, help_text='Complete analysis data including SHAP values')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence 0-1')),
                ('key_features', models.JSONField(default=list, help_text='Most important features for this insight')),
                ('shap_values', models.JSONField(blank=True, default=dict, help_text='SHAP explanation values')),
                ('lime_explanation', models.JSONField(blank=True, default=dict, help_text='LIME local explanation')),
                ('human_explanation', models.TextField(blank=True, help_text='Human-readable explanation')),
                ('is_public', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_insights', to='datasets.dataset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(max_length=50)),
                ('affected_columns', models.JSONField(default=list)),
                ('affected_rows', models.JSONField(default=list)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('anomaly_score', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('visualization_data', models.JSONField(default=dict, help_text='Data for visualizing anomalies')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detections', to='datasets.dataset')),
                ('insight', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detection', to='insights.datainsight')),
            ],
            options={
                'ordering': ['-anomaly_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100)),
                ('target_variable', models.CharField(blank=True, max_length=255)),
                ('shap_summary', models.JSONField(default=dict, help_text='SHAP summary statistics')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance ranking')),
                ('sample_explanations', models.JSONField(default=list, help_text='LIME explanations for samples')),
                ('summary_plot_data', models.JSONField(default=dict)),
                ('force_plot_data', models.JSONField(default=dict)),
                ('dependence_plot_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_explanations', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='OutlierAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('iqr', 'Interquartile Range'), ('zscore', 'Z-Score'), ('isolation_forest', 'Isolation Forest'), ('lof', 'Local Outlier Factor')], max_length=50)),
                ('outlier_indices', models.JSONField(default=list)),
                ('outlier_values', models.JSONField(default=list)),
                ('outlier_count', models.IntegerField()),
                ('outlier_percentage', models.FloatField()),
                ('threshold_values', models.JSONField(default=dict, help_text='Method-specific thresholds')),
                ('statistics', models.JSONField(default=dict, help_text='Statistical summary')),
                ('visualization_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlier_analyses', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_1', models.CharField(max_length=255)),
                ('feature_2', models.CharField(max_length=255)),
                ('correlation_coefficient', models.FloatField()),
                ('p_value', models.FloatField(blank=True, null=True)),
                ('is_significant', models.BooleanField(default=False)),
                ('relationship_type', models.CharField(choices=[('linear', 'Linear'), ('non_linear', 'Non-Linear'), ('inverse', 'Inverse'), ('no_relationship', 'No Relationship')], max_length=50)),
                ('visualization_data', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_analyses', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='InsightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('summary', models.JSONField(default=dict, help_text='Executive summary')),
                ('key_findings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anomalies', models.ManyToManyField(blank=True, related_name='reports', to='insights.anomalydetection')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_reports', to='datasets.dataset')),
                ('insights', models.ManyToManyField(blank=True, related_name='reports', to='insights.datainsight')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_reports', to=settings.AUTH_USER_MODEL)),
                ('outlier_analyses', models.ManyToManyField(blank=True, related_name='reports', to='insights.outlieranalysis')),
                ('relationships', models.ManyToManyField(blank=True, related_name='reports', to='insights.relationshipanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='datainsight',
            index=models.Index(fields=['owner', '-created_at'], name='insights_da_owner_i_3eb721_idx'),
        ),
        migrations.AddIndex(
            model_name='datainsight',
            index=models.Index(fields=['dataset', 'insight_type'], name='insights_da_dataset_be6b48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outlieranalysis',
            unique_together={('dataset', 'column', 'method')},
        ),
    ]
