# Generated by Django 6.0 on 2025-12-10 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_email_verification",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_login_history",
                "ordering": ["-login_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_resets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_password_reset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Regular User"),
                            ("analyst", "Data Analyst"),
                            ("admin", "Administrator"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("US/Eastern", "Eastern Time"),
                            ("US/Central", "Central Time"),
                            ("US/Mountain", "Mountain Time"),
                            ("US/Pacific", "Pacific Time"),
                        ],
                        default="UTC",
                        max_length=50,
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "email_digest",
                    models.BooleanField(
                        default=True, help_text="Receive weekly digest emails"
                    ),
                ),
                (
                    "email_updates",
                    models.BooleanField(
                        default=True, help_text="Receive important updates"
                    ),
                ),
                (
                    "preferred_subscription_tier",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("team", "Team"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="individual",
                        help_text="Preferred subscription tier selected during registration",
                        max_length=20,
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        blank=True,
                        help_text="Team name for Team and Team Plus tiers",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "team_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-5", "1-5 members"),
                            ("5-10", "5-10 members"),
                            ("10-25", "10-25 members"),
                            ("25-50", "25-50 members"),
                            ("50+", "50+ members"),
                        ],
                        help_text="Team size for Team and Team Plus tiers",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True,
                        help_text="Business name for Business and Enterprise tiers",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "business_location",
                    models.CharField(
                        blank=True,
                        help_text="Business location (city, country)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "business_industry",
                    models.CharField(
                        blank=True,
                        help_text="Industry or business sector",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enterprise_name",
                    models.CharField(
                        blank=True,
                        help_text="Enterprise company name",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enterprise_location",
                    models.CharField(
                        blank=True,
                        help_text="Enterprise headquarters location (city, country)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enterprise_industry",
                    models.CharField(
                        blank=True,
                        help_text="Enterprise industry or business sector",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "enterprise_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("100-500", "100-500 employees"),
                            ("500-1000", "500-1,000 employees"),
                            ("1000-5000", "1,000-5,000 employees"),
                            ("5000+", "5,000+ employees"),
                        ],
                        help_text="Enterprise company size",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "enterprise_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Enterprise technical contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("login_count", models.IntegerField(default=0)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("email_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_user_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvitationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_invitation_token",
                "ordering": ["-created_at"],
                "unique_together": {("organization", "email")},
            },
        ),
    ]
