# Generated by Django 6.0 on 2025-12-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="preferred_subscription_tier",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("team", "Team"),
                    ("business", "Business"),
                    ("enterprise", "Enterprise"),
                ],
                default="individual",
                help_text="Preferred subscription tier selected during registration",
                max_length=20,
            ),
        ),
    ]
