# Generated by Django 6.0 on 2025-12-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_preferred_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_industry',
            field=models.CharField(blank=True, help_text='Industry or business sector', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_location',
            field=models.CharField(blank=True, help_text='Business location (city, country)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, help_text='Business name for Business and Enterprise tiers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_name',
            field=models.CharField(blank=True, help_text='Team name for Team and Team Plus tiers', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team_size',
            field=models.CharField(blank=True, choices=[('1-5', '1-5 members'), ('5-10', '5-10 members'), ('10-25', '10-25 members'), ('25-50', '25-50 members'), ('50+', '50+ members')], help_text='Team size for Team and Team Plus tiers', max_length=20, null=True),
        ),
    ]
