# Generated by Django 6.0 on 2025-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_business_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enterprise_contact_email',
            field=models.EmailField(blank=True, help_text='Enterprise technical contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enterprise_industry',
            field=models.CharField(blank=True, help_text='Enterprise industry or business sector', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enterprise_location',
            field=models.CharField(blank=True, help_text='Enterprise headquarters location (city, country)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enterprise_name',
            field=models.CharField(blank=True, help_text='Enterprise company name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enterprise_size',
            field=models.CharField(blank=True, choices=[('100-500', '100-500 employees'), ('500-1000', '500-1,000 employees'), ('1000-5000', '1,000-5,000 employees'), ('5000+', '5,000+ employees')], help_text='Enterprise company size', max_length=20, null=True),
        ),
    ]
